### ISSUE TITLE
Exempi library not found.

### ISSUE THREAD

**Issue by KingUdo** [wahlflo/metadump#1]
I installed the the script as recommended in the read me and have all necessary packages shown when I do a pip freeze 
```
lxml==4.3.3
Pillow==6.0.0
PyPDF2==1.26.0
python-xmp-toolkit==2.0.1
pytz==2019.1
zipfile36==0.1.3
```

But when I start the tool I always get the error "Exempi library not found." even thow the python-xmp-toolkit is installed. What am I missing?

```
python metadump.py -h
Traceback (most recent call last):
  File "metadump.py", line 149, in <module>
    PLUGINS = _load_plugins()
  File "metadump.py", line 145, in _load_plugins
    specification.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "~/metadump/plugins/XMP.py", line 6, in <module>
    from libxmp.utils import file_to_dict
  File "~/metadump/venv/lib/python3.7/site-packages/libxmp/__init__.py", line 50, in <module>
    from .core import XMPMeta, XMPIterator
  File "~/metadump/venv/lib/python3.7/site-packages/libxmp/core.py", line 50, in <module>
    from . import exempi as _cexempi
  File "~/metadump/venv/lib/python3.7/site-packages/libxmp/exempi.py", line 69, in <module>
    EXEMPI = _load_exempi()
  File "~/metadump/venv/lib/python3.7/site-packages/libxmp/exempi.py", line 60, in _load_exempi
    raise ExempiLoadError('Exempi library not found.')
libxmp.ExempiLoadError: Exempi library not found.
```

**Comment by wahlflo** [comment]
Exempi muss über den jeweiligen Paketmanager installiert werden:
`pacman -S exempi`
Ich werde es in die Doku aufnehmen oder es wird automatisch installiert
